#include "./L1JetAnalysis.hh"
// --------------------------------------------------------------------
//                       L1JetAnalysis macro definition
//
//    macro automatically generated by GenerateMacro.sh script
//    author           : bm409
//    creation date    : Sat Oct 23 14:00:25 CEST 2010
//    last update date :
//    description      :
//
// --------------------------------------------------------------------


// --------------------------------------------------------------------
//                             run function
// --------------------------------------------------------------------

void L1JetAnalysis::BookHistos() {



  const int nPtBins = 30;
  double binspt_[nPtBins+1] = { 4.,10.,15.,20.,25.,30.,35.,40.,45.,50.,60.,70.,80.,90.,100.,110.,120.,130.,140.,150.,160.,170.,180.,190.,200.,210.,220.,230.,240.,250.,260. };
  double binseta_[12] = {0.0, 0.348, 0.695, 1.044, 1.392, 1.740, 2.172, 3.0, 3.5, 4.0, 4.5, 5.0 };
  NCenJets = new TH1F("NCenJets","n",20,-0.5,19.5);
  RefJets   = new TH1F("RefJet", "RefJetEt",1000, 0., 1000.);
  L1Jet16   = new TH1F("Jet16" , "JetEt", 1000, 0., 1000.);
  L1Jet20   = new TH1F("Jet20" , "JetEt", 1000, 0., 1000.);
  L1Jet36   = new TH1F("Jet36" , "JetEt", 1000, 0., 1000.);
  L1Jet52   = new TH1F("Jet52" , "JetEt", 1000, 0., 1000.);
  L1Jet68   = new TH1F("Jet68" , "JetEt", 1000, 0., 1000.);
  L1Jet92   = new TH1F("Jet92" , "JetEt", 1000, 0., 1000.);
  L1Jet128  = new TH1F("Jet128" , "JetEt",1000, 0., 1000.);
  L1_EmulatedJet16   = new TH1F("EmulatedJet16" , "JetEt",1000, 0., 1000.);
  L1_EmulatedJet20   = new TH1F("EmulatedJet20" , "JetEt",1000, 0., 1000.);
  L1_EmulatedJet36   = new TH1F("EmulatedJet36" , "JetEt",1000, 0., 1000.);
  L1_EmulatedJet52   = new TH1F("EmulatedJet52" , "JetEt",1000, 0., 1000.);
  L1_EmulatedJet68   = new TH1F("EmulatedJet68" , "JetEt",1000, 0., 1000.);
  L1_EmulatedJet92   = new TH1F("EmulatedJet92" , "JetEt",1000, 0., 1000.);
  L1_EmulatedJet128  = new TH1F("EmulatedJet128", "JetEt",1000, 0., 1000.);
  l1JetEn = new TH1F("L1Energy", "L1Et",1000,0., 1000.);
  l1Jet0 = new TH1F( "l1Jet0", "L1Et",1000,0.,1000.);
  l1Jet1 = new TH1F( "l1Jet1", "L1Et",1000,0.,1000.);
  l1Jet2 = new TH1F( "l1Jet2", "L1Et",1000,0.,1000.);
  l1Jet3 = new TH1F( "l1Jet3", "L1Et",1000,0.,1000.);
  l1Jet4 = new TH1F( "l1Jet4", "L1Et",1000,0.,1000.);
  l1Jet5 = new TH1F( "l1Jet5", "L1Et",1000,0.,1000.);
  dR = new TH1F( "DeltaR", "#delta R", 60,0.,3.2);
  RecoHTL1100 = new TH1F( "RecoHTL1100", "HT", 1000, 0., 1000.);
  RecoHTL1150 = new TH1F( "RecoHTL1150", "HT", 1000, 0., 1000.);
  RecoHTL175  = new TH1F( "RecoHTL175",  "HT", 1000, 0., 1000.);
  RecoHTL150  = new TH1F( "RecoHTL150",  "HT", 1000, 0., 1000.);
  RecoHTL1175 = new TH1F( "RecoHTL1175", "HT", 1000, 0., 1000.);
  RecoHTL1125 = new TH1F( "RecoHTL1125", "HT", 1000, 0., 1000.);
    
    
  Reco_EumulatedHTL1100 = new TH1F( "RecoEmulatedHTL1100", "HT", 1000, 0., 1000.);
  Reco_EumulatedHTL1150 = new TH1F( "RecoEmulatedHTL1150", "HT", 1000, 0., 1000.);
  Reco_EumulatedHTL175  = new TH1F( "RecoEmulatedHTL175",  "HT", 1000, 0., 1000.);
  Reco_EumulatedHTL150  = new TH1F( "RecoEmulatedHTL150",  "HT", 1000, 0., 1000.);
  Reco_EumulatedHTL1175 = new TH1F( "RecoEmulatedHTL1175", "HT", 1000, 0., 1000.);
  Reco_EumulatedHTL1125 = new TH1F( "RecoEmulatedHTL1125", "HT", 1000, 0., 1000.);  
  
  RecoHT = new TH1F( "RecoHT", "HT",1000,0.,1000.);
  recoJetCorrelation = new TH2F( "RecoJetEtvsUnCorRecoJetEt",";Et(UnCorr);Et(Corr)",100,0.,500.,100,0.,500.);
// CandidateJets30Gev = new TH1F("RefJet", "RefJetEt",200,0.,1000);
  RecoVsl1HFE       = new TH2F(     "RecoVsl1HFE",    "Offline Uncorrected Jet Et; L1 Jet Et",1000,0.,1000.,250,0.,1000);
  ResolutionEtHFE   = new TH2F( "ResolutionEtHFE","RecoJetEt;(Reco Jet Et - L1 Jet Et) / Reco Jet Et",500.,0.,500.,200,-10.,10);
  ResolutionHFE     = new TH1F(   "ResolutionHFE",  "(Reco Jet Et - L1 Jet Et) / Reco Jet Et",200,-10.,10);
  RecoVsl1HFH       = new TH2F(     "RecoVsl1HFH",    "Offline Uncorrected Jet Et; L1 Jet Et",250,0.,1000.,250,0.,1000);
  ResolutionEtHFH   = new TH2F( "ResolutionEtHFH","RecoJetEt;(Reco Jet Et - L1 Jet Et) / Reco Jet Et",500.,0.,500.,200,-10.,10);
  ResolutionHFH     = new TH1F(   "ResolutionHFH",  "(Reco Jet Et - L1 Jet Et) / Reco Jet Et",200,-10.,10);
  ResolutionHE      = new TH1F(    "ResolutionHE",   "(Reco Jet Et - L1 Jet Et) / Reco Jet Et",200,-10.,10);
  ResolutionEtHE    = new TH2F(  "ResolutionEtHE", "RecoJetEt;(Reco Jet Et - L1 Jet Et) / Reco Jet Et",500.,0.,500.,200,-10.,10);
  RecoVsl1HE        = new TH2F(      "RecoVsl1HE",     "Offline Uncorrected Jet Et; L1 Jet Et",250,0.,1000.,250,0.,1000);
  ResolutionEE      = new TH1F(    "ResolutionEE",   "(Reco Jet Et - L1 Jet Et) / Reco Jet Et",200,-10.,10);
  ResolutionEtEE    = new TH2F(  "ResolutionEtEE", "RecoJetEt;(Reco Jet Et - L1 Jet Et) / Reco Jet Et",500.,0.,500.,200,-10.,10);
  RecoVsl1EE        = new TH2F(      "RecoVsl1EE",     "Offline Uncorrected Jet Et; L1 Jet Et",250,0.,1000.,250,0.,1000);
  ResolutionHB      = new TH1F(    "ResolutionHB",   "(Reco Jet Et - L1 Jet Et) / Reco Jet Et",200,-10.,10);
  ResolutionEtHB    = new TH2F(  "ResolutionEtHB", "RecoJetEt;(Reco Jet Et - L1 Jet Et) / Reco Jet Et",500.,0.,500.,200,-10.,10);
  RecoVsl1HB        = new TH2F(      "RecoVsl1HB",     "Offline Uncorrected Jet Et; L1 Jet Et",250,0.,1000.,250,0.,1000);
  ResolutionEB      = new TH1F(    "ResolutionEB",   "(Reco Jet Et - L1 Jet Et) / Reco Jet Et",200,-10.,10);
  ResolutionEtEB    = new TH2F(  "ResolutionEtEB", "RecoJetEt;(Reco Jet Et - L1 Jet Et) / Reco Jet Et",500.,0.,500.,200,-10.,10);
  RecoVsl1EB        = new TH2F(      "RecoVsl1EB",     "Offline Uncorrected Jet Et; L1 Jet Et",250,0.,1000.,250,0.,1000);
  EnCorrelation     = new TH2F(   "EnCorrelation",  ";RecoJetEt;L1JetEt",250,0.,1000.,250,0.,1000.);
  EnCorrelation_Eta_0= new TH2F(  "EnCorrelation0", ";RecoJetEt;L1JetEt",250,0.,1000.,250,0.,1000.);
  EnCorrelation_Eta_1= new TH2F(  "EnCorrelation1", ";RecoJetEt;L1JetEt",250,0.,1000.,250,0.,1000.);
  EnCorrelation_Eta_2= new TH2F(  "EnCorrelation2", ";RecoJetEt;L1JetEt",250,0.,1000.,250,0.,1000.);
  EnCorrelation_Eta_3= new TH2F(  "EnCorrelation3", ";RecoJetEt;L1JetEt",250,0.,1000.,250,0.,1000.);
  EnCorrelation_Eta_4= new TH2F(  "EnCorrelation4", ";RecoJetEt;L1JetEt",250,0.,1000.,250,0.,1000.);
  EnCorrelation_Eta_5= new TH2F(  "EnCorrelation5", ";RecoJetEt;L1JetEt",250,0.,1000.,250,0.,1000.);
  EnCorrelation_Eta_6= new TH2F(  "EnCorrelation6", ";RecoJetEt;L1JetEt",250,0.,1000.,250,0.,1000.);
  EnCorrelation_Eta_7= new TH2F(  "EnCorrelation7", ";RecoJetEt;L1JetEt",250,0.,1000.,250,0.,1000.);
  EnCorrelation_Eta_8= new TH2F(  "EnCorrelation8", ";RecoJetEt;L1JetEt",250,0.,1000.,250,0.,1000.);
  EnCorrelation_Eta_9= new TH2F(  "EnCorrelation9", ";RecoJetEt;L1JetEt",250,0.,1000.,250,0.,1000.);
  EnCorrelation_Eta_10= new TH2F( "EnCorrelation10",";RecoJetEt;L1JetEt",250,0.,1000.,250,0.,1000.);
  EnCorrelation_Eta_11= new TH2F( "EnCorrelation11",";RecoJetEt;L1JetEt",250,0.,1000.,250,0.,1000.);
  L1CorVsUnCor      = new TH2F("L1CorVsUnCor", ";L1Corrected;L1UnCOrrected",63,0.,252.,63,0.,252.);
  EMF               = new TH1F("EMF","Jet[0] FEM",100,-1.,1.);
  timeMap           = new TH2I("Bits", "Bunch Crossing vs trigger bit", 130, 0., 130., 10, 0., 10.);
  ResolutionAsFnOfpT = new TH2F("ResolutionAsFnOfpT"," ; L1 P_{T}; #frac{L1 P_{T}}{Reco P_{T}} ",nPtBins ,binspt_ ,200,-10.,10.);
  ResolutionAsFnOfeta = new TH2F("ResolutionAsFnOfeta"," ; L1 #eta;(Reco Jet Et - L1 Jet Et) / Reco Jet Et",20,-5.,5.,200,-10.,10.);
  ResolutionAsFnOfeta_eta3 = new TH2F("ResolutionAsFnOfeta_eta3"," ; L1 #eta;(Reco Jet Et - L1 Jet Et) / Reco Jet Et",20,-5.,5.,200,-10.,10.);
  ResolutionAsFnOfpT_eta3  = new TH2F("ResolutionAsFnOfpT_eta3"," ; L1 P_{T}; #frac{L1 P_{T}}{Reco P_{T}} ",nPtBins ,binspt_ ,200,-10.,10.);
  L1HtRecoJetCorrelation = new TH2F(   "L1HtRecoJetCorrelation", ";RecoJetEt;L1Ht",250,0.,1000.,250,0.,1000.);
  L1HtCorrelation     = new TH2F(   "L1HtCorrelation", ";Reco HT;L1Ht",250,0.,1000.,250,0.,1000.);
  L1SumEtCorrelation     = new TH2F(   "L1SumEtCorrelation", ";Reco E_{T};L1 E_{T}",250,0.,1000.,250,0.,1000.);
  // l1extraSumEtGCTCorrelation = new TH2F(   "l1extraSumEtGCTCorrelation", ";GCT RAW E_{T};L1 E_{T}",10000,-9999999.,1000.,250,0.,1000.);
  MEtCorrelation     = new TH2F(   "MEtCorrelation", ";Reco MET;L1MET",250,0.,1000.,250,0.,1000.);
  L1Ht           = new TH1F("L1HT","",1000,0.,1000.);
  L1mHt          = new TH1F("L1MHT","",1000,0.,1000.);
  L1Et           = new TH1F("L1Et","",1000,0.,1000.);
  L1MEt          = new TH1F("L1MET","",1000,0.,1000.);

  MHT_30U        = new TH1F("MHT30Pass","", 300,0.,300.);
  MHT_20U        = new TH1F("MHT20Pass","", 300,0.,300.);
  MHT_40U        = new TH1F("MHT40Pass","", 300,0.,300.);
  MHT_50U        = new TH1F("MHT50Pass","", 300,0.,300.);
  
  MET_70U        = new TH1F("MET70Pass","", 300,0.,300.);
  MET_40U        = new TH1F("MET40Pass","", 300,0.,300.);
  MET_30U        = new TH1F("MET30Pass","", 300,0.,300.);
  MET_50U        = new TH1F("MET50Pass","", 300,0.,300.);
  MET_20U        = new TH1F("MET20Pass","", 300,0.,300.);
  MET_12U        = new TH1F("MET12Pass","", 300,0.,300.);
  METReference   = new TH1F("METReference","", 300,0.,300.);
  MHTReference   = new TH1F("MHTReference","", 300,0.,300.);
  SumEtReference = new TH1F("SumEtReference","", 250,0.,1000.);
  SumEt_60U = new TH1F("SumEt60","", 250,0.,1000.);
  SumEt_100U = new TH1F("SumEt100","", 250,0.,1000.);
  L1SumEt = new TH1F("L1SumEt","", 250,0.,1000.);

  const double etabins[23]={-5.000,-4.500,-4.000,-3.500,-3.000,-2.172,
  -1.740,-1.392, -1.044,-0.695,-0.348,0.000,0.348,0.695,1.044,1.392,1.740,2.172,3.000,3.500,4.000,4.500,5.000};
    L1EtaPhiMap = new TH2D("etaPhiMapL1","h2" ,22,etabins, 18, -1*TMath::Pi()-0.5, TMath::Pi()-0.5);
    RecoEtaPhiMap = new TH2F("etaPhiMapReco","h2" ,100,-5.,5.0, 31, -1*TMath::Pi()-0.5, TMath::Pi()-0.5);

    TauJetOccupancyAllJets = new TH2D("TauJetOccupancyAllJets","h2",22,etabins,18,-1*TMath::Pi()-0.5, TMath::Pi()-0.5);
    TauJetOccupancyLeadingJet = new TH2D("TauJetOccupancyLeadingJet","h2",22,etabins,18,-1*TMath::Pi()-0.5, TMath::Pi()-0.5);
    ISOEmOccupancyAll = new TH2D("ISOEmOccupancyAll","h2",22,etabins,18,-1*TMath::Pi()-0.5, TMath::Pi()-0.5);
    ISOEmOccupancyLeading = new TH2D("ISOEmOccupancyLeading","h2",22,etabins,18,-1.*TMath::Pi()-0.5, TMath::Pi()-0.5);

  }

// --------------------------------------------------------------------
//                             run function
// --------------------------------------------------------------------
  void L1JetAnalysis::run(Long64_t nevents, TString outputname, TString TriggerBit) //To run use m.run(events,"SomeoutputName","HLT TriggerName") (leave HLT name as white space to select no trigger)
  {
    //Book Histos
    //load TDR style
    TFile *theFile = new TFile(outputname, "RECREATE");
    theFile->cd();
    BookHistos();
    double RecoJetThreshold = 10.;
    double wgt =1.0;
    
    //number of events to process
    if (nevents==-1 || nevents>GetEntries()) nevents=GetEntries();
    std::cout << nevents  << " to process ..." << std::endl;
      //  NB a bit of a hack to read out the correct value from the ReturnMatchedQuantity function -- Didnt know about Enums at the time, will re-write when there is time

    const int Et = 1;
    const int Eta = 2;
    const int Phi = 3;
    double ResolutionET;
    double ResolutionHT;
    double MetReso;
    double MhtReso;
    
    
    
    
    //loop over the events
    
    
    
    
    for (Long64_t i= 0; i<   nevents; i++)
    {
      //load the i-th event
      Long64_t ientry = LoadTree(i); if (ientry < 0) break;
      GetEntry(i);
      //process progress
      if( i!=0 && ( i%10000 ) ==0 ) {std::cout << "- processing event " << i << "\r" << std::flush;}
      // Trigger stuff
      if (!TriggerBit.IsWhitespace() && !PassHLT(TriggerBit) ) continue;
      // Energy sum triggers!
      double flyHT = 0;
      for(unsigned jet = 0; jet < recoJet_->etCorr.size(); jet++){
        if(fabs(recoJet_->eta[jet]) < 3. && recoJet_->etCorr[jet] > 40.) {flyHT += recoJet_->etCorr[jet];}
      }


      // cout <<"Starting HT calculation" << endl;

        ResolutionET = ( l1extra_->et - recoMet_->sumEt  ) / recoMet_->sumEt;
        ResolutionHT = ( l1extra_->ht - flyHT  ) / flyHT;

        MetReso = ( l1extra_->met - recoMet_->met ) / recoMet_->met;
        MhtReso = ( l1extra_->mht - recoMet_->mHt ) / recoMet_->mHt;


        SumEtReference->Fill( recoMet_->sumEt ,wgt);
        if( l1extra_->et > 60.) { SumEt_60U->Fill( recoMet_->sumEt ,wgt);}
        if( l1extra_->et > 100.) { SumEt_100U->Fill( recoMet_->sumEt,wgt);}
        MHTReference->Fill( recoMet_->mHt ,wgt);
        if(l1extra_->mht > 20.) { MHT_20U->Fill(recoMet_->mHt,wgt);}
        if(l1extra_->mht > 30.) { MHT_30U->Fill(recoMet_->mHt,wgt);}
        if(l1extra_->mht > 40.) { MHT_40U->Fill(recoMet_->mHt,wgt);}
        if(l1extra_->mht > 50.) { MHT_50U->Fill(recoMet_->mHt,wgt);}
      
        METReference->Fill( recoMet_->met ,wgt);
        if( l1extra_->met >12. ) { MET_12U->Fill(recoMet_->met,wgt);}
        if( l1extra_->met >20. ) { MET_20U->Fill(recoMet_->met,wgt);}
        if( l1extra_->met >30. ) { MET_30U->Fill(recoMet_->met,wgt);}
        if( l1extra_->met >40. ) { MET_40U->Fill(recoMet_->met,wgt);}
        if( l1extra_->met >50. ) { MET_50U->Fill(recoMet_->met,wgt);}
        if( l1extra_->met >70. ) { MET_70U->Fill(recoMet_->met,wgt);}
        MEtCorrelation->Fill(recoMet_->met,l1extra_->met,wgt);
        L1HtRecoJetCorrelation->Fill(flyHT,l1extra_->ht,wgt);
        L1SumEt->Fill(l1extra_->et,wgt);
        L1SumEtCorrelation->Fill(recoMet_->sumEt,l1extra_->et,wgt);


      // Selection for the turn on curves
      // Note as corrected jets are no longer listed in pt order we now have to find the leading jet
      // Makeshift ENUms

        int leadJet = leadingOfflineJet();
        bool match = MatchJet(leadJet);
        bool matchEmu = MatchEmuJet(leadJet);
        
        recoJetCorrelation->Fill(recoJet_->et[0],recoJet_->etCorr[leadJet],wgt);
        
        if(l1extra_->cenJetEt.size() > 0 && l1emuextra_->cenJetEt.size() > 0){  L1CorVsUnCor->Fill(l1extra_->cenJetEt[0],l1emuextra_->cenJetEt[0]);}



      //  Require only jets Matched to a L1 Jet


        std::pair <int,int> MatchedJet = ReturnMatchedJet(leadJet);
        std::pair <int,int> MatchedEmuJet = ReturnMatchedEmuJet(leadJet);
        // Try to match a L1 Jet to the zeroth reco Jet, return the l1 type and l1 index of
        
        if(ReturnMatchedQuantity(MatchedJet,Et) > 250. ) continue;

        if(recoJet_->etCorr[leadJet]> RecoJetThreshold &&   
           fabs(recoJet_->eta[leadJet])< 3. && LooseID(leadJet) ){ // check leading recoJet is with in
          double MatchedEta = fabs(ReturnMatchedQuantity(MatchedJet,Eta));
          EnCorrelation->Fill(recoJet_->etCorr[leadJet],ReturnMatchedQuantity(MatchedJet,Et),wgt);
          if( MatchedEta < 0.348 ) EnCorrelation_Eta_0->Fill(recoJet_->etCorr[leadJet],ReturnMatchedQuantity(MatchedJet,Et),wgt);
          if( MatchedEta > 0.348 && MatchedEta < 0.695 ) EnCorrelation_Eta_1->Fill(recoJet_->etCorr[leadJet],ReturnMatchedQuantity(MatchedJet,Et),wgt);
          if( MatchedEta > 0.695 && MatchedEta < 1.044 ) EnCorrelation_Eta_2->Fill(recoJet_->etCorr[leadJet],ReturnMatchedQuantity(MatchedJet,Et),wgt);
          if( MatchedEta > 1.044 && MatchedEta < 1.392 ) EnCorrelation_Eta_3->Fill(recoJet_->etCorr[leadJet],ReturnMatchedQuantity(MatchedJet,Et),wgt);
          if( MatchedEta > 1.392 && MatchedEta < 1.740 ) EnCorrelation_Eta_4->Fill(recoJet_->etCorr[leadJet],ReturnMatchedQuantity(MatchedJet,Et),wgt);
          if( MatchedEta > 1.740 && MatchedEta < 2.172 ) EnCorrelation_Eta_5->Fill(recoJet_->etCorr[leadJet],ReturnMatchedQuantity(MatchedJet,Et),wgt);
          if( MatchedEta > 2.172 && MatchedEta < 3.000 ) EnCorrelation_Eta_6->Fill(recoJet_->etCorr[leadJet],ReturnMatchedQuantity(MatchedJet,Et),wgt);
          if( MatchedEta > 3.000 && MatchedEta < 3.500 ) EnCorrelation_Eta_7->Fill(recoJet_->etCorr[leadJet],ReturnMatchedQuantity(MatchedJet,Et),wgt);
          if( MatchedEta > 3.500 && MatchedEta < 4.000 ) EnCorrelation_Eta_8->Fill(recoJet_->etCorr[leadJet],ReturnMatchedQuantity(MatchedJet,Et),wgt);
          if( MatchedEta > 4.000 && MatchedEta < 4.500 ) EnCorrelation_Eta_9->Fill(recoJet_->etCorr[leadJet],ReturnMatchedQuantity(MatchedJet,Et),wgt);
          if( MatchedEta > 4.500 && MatchedEta < 5.000 ) EnCorrelation_Eta_10->Fill(recoJet_->etCorr[leadJet],ReturnMatchedQuantity(MatchedJet,Et),wgt);
          if( MatchedEta > 5.000  ) EnCorrelation_Eta_11->Fill(recoJet_->etCorr[leadJet],ReturnMatchedQuantity(MatchedJet,Et),wgt);





          dR->Fill(deltaR(recoJet_->eta[leadJet], recoJet_->phi[leadJet], 
                          ReturnMatchedQuantity(MatchedJet,Eta),
                          ReturnMatchedQuantity(MatchedJet,Phi)),wgt);


         
          
          RecoEtaPhiMap->Fill(recoJet_->eta[leadJet],recoJet_->phi[leadJet],wgt);
          L1EtaPhiMap->Fill(ReturnMatchedQuantity(MatchedJet,Eta),
                            ReturnMatchedQuantity(MatchedJet,Phi),wgt);
          l1JetEn->Fill(ReturnMatchedQuantity(MatchedJet,Et),wgt);
          RefJets->Fill(recoJet_->etCorr[leadJet],wgt); // Denominator for turn on curves

        // Ask for Corrected L1 Jets -- Use on 2011 Data
      if(match){
          if( ReturnMatchedQuantity(MatchedJet,Et) >16.)  {L1Jet16->Fill( recoJet_->etCorr[leadJet],wgt);} 
          if( ReturnMatchedQuantity(MatchedJet,Et) > 20.) {L1Jet20->Fill( recoJet_->etCorr[leadJet],wgt);}
          if( ReturnMatchedQuantity(MatchedJet,Et) > 36.) {L1Jet36->Fill( recoJet_->etCorr[leadJet],wgt);}
          if( ReturnMatchedQuantity(MatchedJet,Et) > 52.) {L1Jet52->Fill( recoJet_->etCorr[leadJet],wgt);}
          if( ReturnMatchedQuantity(MatchedJet,Et) > 68.) {L1Jet68->Fill( recoJet_->etCorr[leadJet],wgt);}
          if( ReturnMatchedQuantity(MatchedJet,Et) > 92.) {L1Jet92->Fill( recoJet_->etCorr[leadJet],wgt);}
          if( ReturnMatchedQuantity(MatchedJet,Et) > 128.){L1Jet128->Fill(recoJet_->etCorr[leadJet],wgt);}
      }


       if(matchEmu){
          if( ReturnMatchedEmuQuantity(MatchedEmuJet,Et) >16.)  {L1_EmulatedJet16->Fill( recoJet_->etCorr[leadJet],wgt);} 
          if( ReturnMatchedEmuQuantity(MatchedEmuJet,Et) > 20.) {L1_EmulatedJet20->Fill( recoJet_->etCorr[leadJet],wgt);}
          if( ReturnMatchedEmuQuantity(MatchedEmuJet,Et) > 36.) {L1_EmulatedJet36->Fill( recoJet_->etCorr[leadJet],wgt);}
          if( ReturnMatchedEmuQuantity(MatchedEmuJet,Et) > 52.) {L1_EmulatedJet52->Fill( recoJet_->etCorr[leadJet],wgt);}
          if( ReturnMatchedEmuQuantity(MatchedEmuJet,Et) > 68.) {L1_EmulatedJet68->Fill( recoJet_->etCorr[leadJet],wgt);}
          if( ReturnMatchedEmuQuantity(MatchedEmuJet,Et) > 92.) {L1_EmulatedJet92->Fill( recoJet_->etCorr[leadJet],wgt);}
          if( ReturnMatchedEmuQuantity(MatchedEmuJet,Et) > 128.){L1_EmulatedJet128->Fill(recoJet_->etCorr[leadJet],wgt);}
        }


          
        

 


    // Timing studies
        for(size_t bx = 0; bx < 5; ++bx)
        {
          for(size_t bit = 0; bit < 128; ++bit)
          {
            if(PassTrig(bit,bx)){
              timeMap->Fill(bit,bx,wgt);
            }
          }
        }

      }
    //  Write out the files so we can make eff curves etc - do this outside of the macro so we can run // on the batch
    // Write and close the file!
      theFile->Write();
      theFile->Close();

    }
